apiVersion: v1
kind: Service
metadata:
  namespace: todo-cn-app
  name: todoqueryservice
  labels:
    app: todoqueryservice
spec:
  type: NodePort
  ports:
  - port: 9082
    name: todoqueryservice
    targetPort: 9082
  selector:
    app: todoqueryservice
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: todo-cn-app
  name: todoqueryservice
  labels:
    app: todoqueryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoqueryservice
  template:
    metadata:
      labels:
        app: todoqueryservice
    spec:
      containers:
      - name: todoqueryservice
        image: mirna/todoqueryservice
        ports:
        - containerPort: 9082
        env:
        - name: EUREKA_URL
          value: "http://todoserviceregistry:8761/eureka"
        - name: DB_URL
          value: "//todo-db:3306/mydb"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "password"
        - name: SERVER_PORT
          value: "9082"                    



    
    