apiVersion: v1
kind: Service
metadata:
  namespace: todo-cn-app
  name: todoserviceregistry
  labels:
    app: todoserviceregistry
spec:
  type: NodePort
  ports:
  - port: 8761
    name: todoserviceregistry
    targetPort: 8761
  selector:
    app: todoserviceregistry
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: todo-cn-app
  name: todoserviceregistry
  labels:
    app: todoserviceregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoserviceregistry
  template:
    metadata:
      labels:
        app: todoserviceregistry
    spec:
      containers:
      - name: todoserviceregistry
        image: mirna/todoserviceregistry
        ports:
        - containerPort: 8761
        env:
        - name: SERVER_PORT
          value: "8761"

    
    