spring:
  application:
    name: ToDoUIService
  profiles:
    active: "cloud"

---

spring:
  profiles: local
  
server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${server.port}

---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}                                                
    instanceId: ${vcap.application.instance_id}
  client:
    service-url:
      defaultZone: http://todoserviceregistry.local.pcfdev.io/eureka/