spring:
  application:
    name: ToDoQueryService
  profiles:
    active: "cloud"

---

spring:
  profiles: local
  jpa:
    hibernate:
     ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: password

server:
  port: 9082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${server.port}

---

spring:
  profiles: cloud
  jpa:
   hibernate:
    ddl-auto: create
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}                                                 
    instanceId: ${vcap.application.instance_id}
  client:
    service-url:
      defaultZone: http://todoserviceregistry.local.pcfdev.io/eureka/
      
      
    
    
    
    