spring:
  application:
    name: ToDoServiceRegistry
  profiles:
    active: "cloud"


---
spring:
  profiles: local


server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---

spring:
  profiles: cloud

eureka:
  instance:
    nonSecurePort: 8761
    hostname: ${vcap.application.uris[0]}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://todoserviceregistry.local.pcfdev.io/eureka/
      